### ISSUE TITLE
bug: Tag 0.1.2 Fails execution

### ISSUE THREAD

**Issue by Gonmeso** [gizatechxyz/scarb-agent#27]
# Bug Report

**Scarb Agent version:** 0.1.2

**Current behavior:** Execution of the agent fails when in v.0.1.1 worked. Error is `{"message":"Memory addresses must be relocatable","status":"error"}`

**Expected behaviour:** With the addition of the yaml schema execution should still work as nothing but scarb agent has worked

**Steps to reproduce:**

clone mode agent: `git clone git@github.com:gizatechxyz/agent_mode.git`

install scarb-agent.

Add the following `cairo_schema.yaml`:

```yaml
schemas:
  Input:
    fields:
      wallet:
        type: Primitive
        name: ByteArray
      has_deposits:
        type: Primitive
        name: bool
      user_token_address:
        type: Primitive
        name: ByteArray
      amount:
        type: Primitive
        name: i64
      user_current_protocol:
        type: Primitive
        name: ByteArray
cairo_input: Input
cairo_output: None
```

Start python server

Run Agent with:

```
scarb agent-run  --args '{
  "user_token_address": "0xf0F161fDA2712DB8b566946122a5af183995e2eD",
  "has_deposits": false,
  "amount": 1,
  "wallet": "0xe2e2C18CC8f3Ba72013AaB13244f740f0f320B37",
  "user_current_protocol": "0xe2e2C18CC8f3Ba72013AaB13244f740f0f320B37"
}'
```

Output:

`{"message":"Memory addresses must be relocatable","status":"error"}`

**Other information:**

If you install the tag v0.1.1 it works using the previous schema.

`cargo install --git https://github.com/gizatechxyz/scarb-agent --tag 0.1.1`

Output:

```
{"data":{"0":{}},"status":"success"}
```

@raphaelDkhn
